version: "3"
services:
  wppconnect-server:
    build: ./
    network_mode: "host"
    restart: always
    image: wppconnect-server
    container_name: wppconnect-server-1
    hostname: wppconnect-server-1
    entrypoint: docker-entrypoint.sh yarn dev
